# Generated by Django 2.2.7 on 2020-03-07 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
